import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CssVarsProvider } from '@mui/joy/styles';
import CssBaseline from '@mui/joy/CssBaseline';
import Sidebar from "@/components/Sidebar";
import Header from '@/components/Header';
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import Box from '@mui/joy/Box';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <CssVarsProvider disableTransitionOnChange>
          <CssBaseline />
          <ReduxProvider>
            <NextAuthProvider session={session}>
              <Box sx={{ display: 'flex', minHeight: '100dvh' }}>
                <Sidebar session={session} />
                <Header />
                <Box
                  component="main"
                  className="MainContent"
                  sx={{
                    pt: { xs: 'calc(12px + var(--Header-height))', md: 3 },
                    pb: { xs: 2, sm: 2, md: 3 },
                    flex: 1,
                    display: 'flex',
                    flexDirection: 'column',
                    minWidth: 0,
                    height: '100dvh',
                    gap: 1,
                    overflow: 'auto',
                  }}
                >
                  {children}
                </Box>
              </Box>
            </NextAuthProvider>
          </ReduxProvider>
        </CssVarsProvider>
      </body>
    </html>
  );
}
